name: universal_notes_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.1.1
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  file_picker: ^8.0.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  fluent_ui: ^4.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  flutter_tts: ^4.0.2
  http: ^1.6.0
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  meta: ^1.17.0
  open_file: ^3.5.10
  opentelemetry: ^0.18.10
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^12.0.1
  printing: ^5.12.0
  provider: ^6.1.5
  pub_semver: ^2.1.4
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  sqflite_common_ffi: 2.3.0
  url_launcher: ^6.3.0
  uuid: ^4.5.2
  window_manager: ^0.5.1

dev_dependencies:
  alchemist: ^0.13.0
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.1.2
  test: ^1.24.0
  test_api: ^0.7.7
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dictionaries/
